version: '3.8'
services:
  web:
    build: .
    ports:
      - '3000:3000'
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
      - NEXT_TELEMETRY_DISABLED=1
      - NEXT_PUBLIC_SUPABASE_URL
      - NEXT_PUBLIC_SUPABASE_ANON_KEY
      - SUPABASE_SERVICE_ROLE_KEY

  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: veilpass
      POSTGRES_PASSWORD: veilpass
      POSTGRES_DB: veilpass
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

volumes:
  db-data:
